#define __USE_GNU
#define _GNU_SOURCE
#define ON_MACOS
//#define HAVE_POSIX_FALLOCATE
//#define HAVE_FDATASYNC
//#define HAVE_SYNC_FILE_RANGE
//#define HAVE_O_NOATIME
//#define HAVE_POSIX_FADVISE
#define HAVE_O_DIRECT
#define HAVE_GCC_ATOMICS
#define HAVE_PTHREAD_STACK_MIN
#define HAVE_ALLOCA_H
#define HAVE_TDESTROY
#define HAVE_POWL
#define PBL_COMPAT 1
#define STLSEARCH 1
//#define DBUG
